export interface GameWord {
  word: string;
  clue: string;
  category: string;
}

export const gameWords: GameWord[] = [
  // 📍 Places
  { word: "Beach", clue: "Waves", category: "📍 Places" },
  { word: "Hospital", clue: "Scrubs", category: "📍 Places" },
  { word: "Restaurant", clue: "Menu", category: "📍 Places" },
  { word: "Library", clue: "Shelves", category: "📍 Places" },
  { word: "Airport", clue: "Boarding", category: "📍 Places" },
  { word: "Gym", clue: "Reps", category: "📍 Places" },
  { word: "Museum", clue: "Exhibits", category: "📍 Places" },
  { word: "Casino", clue: "Chips", category: "📍 Places" },
  { word: "Stadium", clue: "Bleachers", category: "📍 Places" },
  { word: "Spa", clue: "Massage", category: "📍 Places" },
  { word: "Aquarium", clue: "Tanks", category: "📍 Places" },
  { word: "Bakery", clue: "Dough", category: "📍 Places" },
  { word: "Prison", clue: "Bars", category: "📍 Places" },
  { word: "Theater", clue: "Curtain", category: "📍 Places" },
  { word: "Subway", clue: "Tunnel", category: "📍 Places" },

  // 💼 Professions
  { word: "Doctor", clue: "Diagnosis", category: "💼 Professions" },
  { word: "Chef", clue: "Sauté", category: "💼 💼 Professions" },
  { word: "Pilot", clue: "Cockpit", category: "💼 Professions" },
  { word: "Teacher", clue: "Chalk", category: "💼 Professions" },
  { word: "Firefighter", clue: "Hose", category: "💼 Professions" },
  { word: "Lawyer", clue: "Brief", category: "💼 Professions" },
  { word: "Photographer", clue: "Shutter", category: "💼 Professions" },
  { word: "Mechanic", clue: "Wrench", category: "💼 Professions" },
  { word: "Astronaut", clue: "Orbit", category: "💼 Professions" },
  { word: "Bartender", clue: "Shaker", category: "💼 Professions" },
  { word: "Journalist", clue: "Headline", category: "💼 Professions" },
  { word: "Plumber", clue: "Pipe", category: "💼 Professions" },
  { word: "Detective", clue: "Clues", category: "💼 Professions" },
  { word: "Fisherman", clue: "Bait", category: "💼 Professions" },
  { word: "Architect", clue: "Sketch", category: "💼 Professions" },

  // 🍔 Food & Drinks
  { word: "Pizza", clue: "Crust", category: "🍔 Food & Drinks" },
  { word: "Sushi", clue: "Rice", category: "🍔 Food & Drinks" },
  { word: "Coffee", clue: "Beans", category: "🍔 Food & Drinks" },
  { word: "Burger", clue: "Bun", category: "🍔 Food & Drinks" },
  { word: "Tacos", clue: "Folded", category: "🍔 Food & Drinks" },
  { word: "Ice Cream", clue: "Scoop", category: "🍔 Food & Drinks" },
  { word: "Pasta", clue: "Noodles", category: "🍔 Food & Drinks" },
  { word: "Chocolate", clue: "Cocoa", category: "🍔 Food & Drinks" },
  { word: "Soup", clue: "Broth", category: "🍔 Food & Drinks" },
  { word: "Wine", clue: "Grape", category: "🍔 Food & Drinks" },
  { word: "Salad", clue: "Tossed", category: "🍔 Food & Drinks" },
  { word: "Steak", clue: "Sear", category: "🍔 Food & Drinks" },
  { word: "Pancakes", clue: "Syrup", category: "🍔 Food & Drinks" },
  { word: "Popcorn", clue: "Kernels", category: "🍔 Food & Drinks" },
  { word: "Smoothie", clue: "Fruit", category: "🍔 Food & Drinks" },

  // 🐾 Animals
  { word: "Elephant", clue: "Tusks", category: "🐾 Animals" },
  { word: "Dolphin", clue: "Clicks", category: "🐾 Animals" },
  { word: "Eagle", clue: "Talons", category: "🐾 Animals" },
  { word: "Kangaroo", clue: "Pouch", category: "🐾 Animals" },
  { word: "Penguin", clue: "Tuxedo", category: "🐾 Animals" },
  { word: "Lion", clue: "Mane", category: "🐾 Animals" },
  { word: "Owl", clue: "Hoot", category: "🐾 Animals" },
  { word: "Shark", clue: "Fins", category: "🐾 Animals" },
  { word: "Butterfly", clue: "Cocoon", category: "🐾 Animals" },
  { word: "Giraffe", clue: "Spots", category: "🐾 Animals" },
  { word: "Octopus", clue: "Ink", category: "🐾 Animals" },
  { word: "Cheetah", clue: "Sprint", category: "🐾 Animals" },
  { word: "Panda", clue: "Monochrome", category: "🐾 Animals" },
  { word: "Sloth", clue: "Hanging", category: "🐾 Animals" },
  { word: "Peacock", clue: "Feathers", category: "🐾 Animals" },

  // Sports & Activities
  { word: "Basketball", clue: "Bounce", category: "Sports & Activities" },
  { word: "Swimming", clue: "Stroke", category: "Sports & Activities" },
  { word: "Soccer", clue: "Kick", category: "Sports & Activities" },
  { word: "Golf", clue: "Swing", category: "Sports & Activities" },
  { word: "Tennis", clue: "Serve", category: "Sports & Activities" },
  { word: "Boxing", clue: "Jab", category: "Sports & Activities" },
  { word: "Skiing", clue: "Poles", category: "Sports & Activities" },
  { word: "Surfing", clue: "Board", category: "Sports & Activities" },
  { word: "Bowling", clue: "Strike", category: "Sports & Activities" },
  { word: "Yoga", clue: "Pose", category: "Sports & Activities" },
  { word: "Archery", clue: "Arrow", category: "Sports & Activities" },
  { word: "Marathon", clue: "Distance", category: "Sports & Activities" },
  { word: "Chess", clue: "Checkmate", category: "Sports & Activities" },
  { word: "Cycling", clue: "Gears", category: "Sports & Activities" },
  { word: "Fencing", clue: "Foil", category: "Sports & Activities" },

  // 📱 Technology & Gadgets
  { word: "Smartphone", clue: "Apps", category: "📱 Technology & Gadgets" },
  { word: "Laptop", clue: "Keyboard", category: "📱 Technology & Gadgets" },
  { word: "Headphones", clue: "Noise", category: "📱 Technology & Gadgets" },
  { word: "Camera", clue: "Shutter", category: "📱 Technology & Gadgets" },
  { word: "Tablet", clue: "Stylus", category: "📱 Technology & Gadgets" },
  { word: "Smartwatch", clue: "Notifications", category: "📱 Technology & Gadgets" },
  { word: "Drone", clue: "Aerial", category: "📱 Technology & Gadgets" },
  { word: "Router", clue: "Signal", category: "📱 Technology & Gadgets" },
  { word: "Console", clue: "Controller", category: "📱 Technology & Gadgets" },
  { word: "Bluetooth Speaker", clue: "Pairing", category: "📱 Technology & Gadgets" },
  { word: "VR Headset", clue: "Virtual", category: "📱 Technology & Gadgets" },
  { word: "Keyboard", clue: "Keys", category: "📱 Technology & Gadgets" },
  { word: "Microphone", clue: "Volume", category: "📱 Technology & Gadgets" },
  { word: "Charger", clue: "Battery", category: "📱 Technology & Gadgets" },
  { word: "Projector", clue: "Beam", category: "📱 Technology & Gadgets" },

  // 🚗 Vehicles
  { word: "Bicycle", clue: "Chain", category: "🚗 Vehicles" },
  { word: "Motorcycle", clue: "Throttle", category: "🚗 Vehicles" },
  { word: "Helicopter", clue: "Blades", category: "🚗 Vehicles" },
  { word: "Submarine", clue: "Periscope", category: "🚗 Vehicles" },
  { word: "Train", clue: "Rails", category: "🚗 Vehicles" },
  { word: "Bus", clue: "Route", category: "🚗 Vehicles" },
  { word: "Yacht", clue: "Sail", category: "🚗 Vehicles" },
  { word: "Ambulance", clue: "Stretcher", category: "🚗 Vehicles" },
  { word: "Truck", clue: "Haul", category: "🚗 Vehicles" },
  { word: "Scooter", clue: "Kickstand", category: "🚗 Vehicles" },
  { word: "Jet", clue: "Turbine", category: "🚗 Vehicles" },
  { word: "Boat", clue: "Oar", category: "🚗 Vehicles" },
  { word: "Taxi", clue: "Meter", category: "🚗 Vehicles" },
  { word: "Skateboard", clue: "Deck", category: "🚗 Vehicles" },
  { word: "Hot Air Balloon", clue: "Burner", category: "🚗 Vehicles" },

  // 🎬 Movies & TV Show
  { word: "Titanic", clue: "Sink", category: "🎬 Movies & TV Show" },
  { word: "Friends", clue: "Central", category: "🎬 Movies & TV Show" },
  { word: "Avatar", clue: "Pandora", category: "🎬 Movies & TV Show" },
  { word: "Breaking Bad", clue: "Meth", category: "🎬 Movies & TV Show" },
  { word: "Harry Potter", clue: "Wand", category: "🎬 Movies & TV Show" },
  { word: "The Office", clue: "Dundies", category: "🎬 Movies & TV Show" },
  { word: "Jaws", clue: "Shark", category: "🎬 Movies & TV Show" },
  { word: "Stranger Things", clue: "Demogorgon", category: "🎬 Movies & TV Show" },
  { word: "Frozen", clue: "Elsa", category: "🎬 Movies & TV Show" },
  { word: "Game of Thrones", clue: "Dragons", category: "🎬 Movies & TV Show" },
  { word: "The Matrix", clue: "Pills", category: "🎬 Movies & TV Show" },
  { word: "Spongebob", clue: "Pineapple", category: "🎬 Movies & TV Show" },
  { word: "Inception", clue: "Totem", category: "🎬 Movies & TV Show" },
  { word: "The Simpsons", clue: "Springfield", category: "🎬 Movies & TV Show" },
  { word: "Jurassic Park", clue: "Dinosaurs", category: "🎬 Movies & TV Show" },

  // 🎨 Hobbies & Interests
  { word: "Reading", clue: "Bookmark", category: "🎨 Hobbies & Interests" },
  { word: "Painting", clue: "Brush", category: "🎨 Hobbies & Interests" },
  { word: "Gardening", clue: "Soil", category: "🎨 Hobbies & Interests" },
  { word: "Cooking", clue: "Seasoning", category: "🎨 Hobbies & Interests" },
  { word: "Dancing", clue: "Steps", category: "🎨 Hobbies & Interests" },
  { word: "Photography", clue: "Focus", category: "🎨 Hobbies & Interests" },
  { word: "Knitting", clue: "Needles", category: "🎨 Hobbies & Interests" },
  { word: "Fishing", clue: "Rod", category: "🎨 Hobbies & Interests" },
  { word: "Hiking", clue: "Boots", category: "🎨 Hobbies & Interests" },
  { word: "Gaming", clue: "Levels", category: "🎨 Hobbies & Interests" },
  { word: "Collecting", clue: "Display", category: "🎨 Hobbies & Interests" },
  { word: "Singing", clue: "Pitch", category: "🎨 Hobbies & Interests" },
  { word: "Writing", clue: "Draft", category: "🎨 Hobbies & Interests" },
  { word: "Camping", clue: "Bonfire", category: "🎨 Hobbies & Interests" },
  { word: "Baking", clue: "Flour", category: "🎨 Hobbies & Interests" },

  // 🏠 Household Objects
  { word: "Refrigerator", clue: "Frost", category: "🏠 Household Objects" },
  { word: "Sofa", clue: "Cushion", category: "🏠 Household Objects" },
  { word: "Lamp", clue: "Bulb", category: "🏠 Household Objects" },
  { word: "Microwave", clue: "Beep", category: "🏠 Household Objects" },
  { word: "Mirror", clue: "Glass", category: "🏠 Household Objects" },
  { word: "Pillow", clue: "Feathers", category: "🏠 Household Objects" },
  { word: "Vacuum", clue: "Dust", category: "🏠 Household Objects" },
  { word: "Clock", clue: "Tick", category: "🏠 Household Objects" },
  { word: "Blender", clue: "Puree", category: "🏠 Household Objects" },
  { word: "Curtains", clue: "Fabric", category: "🏠 Household Objects" },
  { word: "Trash Can", clue: "Lid", category: "🏠 Household Objects" },
  { word: "Toaster", clue: "Slots", category: "🏠 Household Objects" },
  { word: "Fan", clue: "Blades", category: "🏠 Household Objects" },
  { word: "Doormat", clue: "Entry", category: "🏠 Household Objects" },
  { word: "Blanket", clue: "Cozy", category: "🏠 Household Objects" }
];

export default gameWords;