export interface GameWord {
  word: string;
  clue: string;
  category: string;
}

export const gameWords: GameWord[] = [
  // 📍 Places
  { word: "Beach", clue: "Tide", category: "📍 Places" },
  { word: "Hospital", clue: "Sterile", category: "📍 Places" },
  { word: "Restaurant", clue: "Gratuity", category: "📍 Places" },
  { word: "Library", clue: "Dewey", category: "📍 Places" },
  { word: "Airport", clue: "Terminal", category: "📍 Places" },
  { word: "Gym", clue: "Chalk", category: "📍 Places" },
  { word: "Museum", clue: "Curator", category: "📍 Places" },
  { word: "Casino", clue: "Ante", category: "📍 Places" },
  { word: "Stadium", clue: "Capacity", category: "📍 Places" },
  { word: "Spa", clue: "Robes", category: "📍 Places" },
  { word: "Aquarium", clue: "Glass", category: "📍 Places" },
  { word: "Bakery", clue: "Yeast", category: "📍 Places" },
  { word: "Prison", clue: "Sentence", category: "📍 Places" },
  { word: "Theater", clue: "Intermission", category: "📍 Places" },
  { word: "Subway", clue: "Commute", category: "📍 Places" },

  // 💼 Professions
  { word: "Doctor", clue: "Rounds", category: "💼 Professions" },
  { word: "Chef", clue: "Whisk", category: "💼 Professions" },
  { word: "Pilot", clue: "Altitude", category: "💼 Professions" },
  { word: "Teacher", clue: "Roster", category: "💼 Professions" },
  { word: "Firefighter", clue: "Hydrant", category: "💼 Professions" },
  { word: "Lawyer", clue: "Bar", category: "💼 Professions" },
  { word: "Photographer", clue: "Aperture", category: "💼 Professions" },
  { word: "Mechanic", clue: "Grease", category: "💼 Professions" },
  { word: "Astronaut", clue: "Gravity", category: "💼 Professions" },
  { word: "Bartender", clue: "Draft", category: "💼 Professions" },
  { word: "Journalist", clue: "Source", category: "💼 Professions" },
  { word: "Plumber", clue: "Clog", category: "💼 Professions" },
  { word: "Detective", clue: "Alibi", category: "💼 Professions" },
  { word: "Fisherman", clue: "Net", category: "💼 Professions" },
  { word: "Architect", clue: "Blueprint", category: "💼 Professions" },

  // 🍔 Food & Drinks
  { word: "Pizza", clue: "Triangle", category: "🍔 Food & Drinks" },
  { word: "Sushi", clue: "Raw", category: "🍔 Food & Drinks" },
  { word: "Coffee", clue: "Caffeine", category: "🍔 Food & Drinks" },
  { word: "Burger", clue: "Patty", category: "🍔 Food & Drinks" },
  { word: "Tacos", clue: "Shell", category: "🍔 Food & Drinks" },
  { word: "Ice Cream", clue: "Cone", category: "🍔 Food & Drinks" },
  { word: "Pasta", clue: "Durum", category: "🍔 Food & Drinks" },
  { word: "Chocolate", clue: "Bar", category: "🍔 Food & Drinks" },
  { word: "Soup", clue: "Ladle", category: "🍔 Food & Drinks" },
  { word: "Wine", clue: "Cellar", category: "🍔 Food & Drinks" },
  { word: "Salad", clue: "Dressing", category: "🍔 Food & Drinks" },
  { word: "Steak", clue: "Rare", category: "🍔 Food & Drinks" },
  { word: "Pancakes", clue: "Stack", category: "🍔 Food & Drinks" },
  { word: "Popcorn", clue: "Cinema", category: "🍔 Food & Drinks" },
  { word: "Smoothie", clue: "Straw", category: "🍔 Food & Drinks" },

  // 🐾 Animals
  { word: "Elephant", clue: "Ivory", category: "🐾 Animals" },
  { word: "Dolphin", clue: "Pod", category: "🐾 Animals" },
  { word: "Eagle", clue: "Nest", category: "🐾 Animals" },
  { word: "Kangaroo", clue: "Joey", category: "🐾 Animals" },
  { word: "Penguin", clue: "Ice", category: "🐾 Animals" },
  { word: "Lion", clue: "Pride", category: "🐾 Animals" },
  { word: "Owl", clue: "Nocturnal", category: "🐾 Animals" },
  { word: "Shark", clue: "Jaw", category: "🐾 Animals" },
  { word: "Butterfly", clue: "Wings", category: "🐾 Animals" },
  { word: "Giraffe", clue: "Neck", category: "🐾 Animals" },
  { word: "Octopus", clue: "Tentacles", category: "🐾 Animals" },
  { word: "Cheetah", clue: "Spots", category: "🐾 Animals" },
  { word: "Panda", clue: "Bamboo", category: "🐾 Animals" },
  { word: "Sloth", clue: "Slow", category: "🐾 Animals" },
  { word: "Peacock", clue: "Fan", category: "🐾 Animals" },

  // Sports & Activities
  { word: "Basketball", clue: "Hoop", category: "Sports & Activities" },
  { word: "Swimming", clue: "Pool", category: "Sports & Activities" },
  { word: "Soccer", clue: "Goal", category: "Sports & Activities" },
  { word: "Golf", clue: "Tee", category: "Sports & Activities" },
  { word: "Tennis", clue: "Court", category: "Sports & Activities" },
  { word: "Boxing", clue: "Ring", category: "Sports & Activities" },
  { word: "Skiing", clue: "Snow", category: "Sports & Activities" },
  { word: "Surfing", clue: "Ocean", category: "Sports & Activities" },
  { word: "Bowling", clue: "Pins", category: "Sports & Activities" },
  { word: "Yoga", clue: "Mat", category: "Sports & Activities" },
  { word: "Archery", clue: "Target", category: "Sports & Activities" },
  { word: "Marathon", clue: "Race", category: "Sports & Activities" },
  { word: "Chess", clue: "Board", category: "Sports & Activities" },
  { word: "Cycling", clue: "Pedal", category: "Sports & Activities" },
  { word: "Fencing", clue: "Sword", category: "Sports & Activities" },

  // 📱 Technology & Gadgets
  { word: "Smartphone", clue: "Touch", category: "📱 Technology & Gadgets" },
  { word: "Laptop", clue: "Screen", category: "📱 Technology & Gadgets" },
  { word: "Headphones", clue: "Ear", category: "📱 Technology & Gadgets" },
  { word: "Camera", clue: "Lens", category: "📱 Technology & Gadgets" },
  { word: "Tablet", clue: "Flat", category: "📱 Technology & Gadgets" },
  { word: "Smartwatch", clue: "Wrist", category: "📱 Technology & Gadgets" },
  { word: "Drone", clue: "Fly", category: "📱 Technology & Gadgets" },
  { word: "Router", clue: "Wi-Fi", category: "📱 Technology & Gadgets" },
  { word: "Console", clue: "Game", category: "📱 Technology & Gadgets" },
  { word: "Bluetooth Speaker", clue: "Sound", category: "📱 Technology & Gadgets" },
  { word: "VR Headset", clue: "Eyes", category: "📱 Technology & Gadgets" },
  { word: "Keyboard", clue: "Type", category: "📱 Technology & Gadgets" },
  { word: "Microphone", clue: "Voice", category: "📱 Technology & Gadgets" },
  { word: "Charger", clue: "Power", category: "📱 Technology & Gadgets" },
  { word: "Projector", clue: "Wall", category: "📱 Technology & Gadgets" },

  // 🚗 Vehicles
  { word: "Bicycle", clue: "Two-wheel", category: "🚗 Vehicles" },
  { word: "Motorcycle", clue: "Helmet", category: "🚗 Vehicles" },
  { word: "Helicopter", clue: "Propeller", category: "🚗 Vehicles" },
  { word: "Submarine", clue: "Underwater", category: "🚗 Vehicles" },
  { word: "Train", clue: "Track", category: "🚗 Vehicles" },
  { word: "Bus", clue: "Stop", category: "🚗 Vehicles" },
  { word: "Yacht", clue: "Luxury", category: "🚗 Vehicles" },
  { word: "Ambulance", clue: "Emergency", category: "🚗 Vehicles" },
  { word: "Truck", clue: "Cargo", category: "🚗 Vehicles" },
  { word: "Scooter", clue: "Small", category: "🚗 Vehicles" },
  { word: "Jet", clue: "Fast", category: "🚗 Vehicles" },
  { word: "Boat", clue: "Water", category: "🚗 Vehicles" },
  { word: "Taxi", clue: "Fare", category: "🚗 Vehicles" },
  { word: "Skateboard", clue: "Roll", category: "🚗 Vehicles" },
  { word: "Hot Air Balloon", clue: "Sky", category: "🚗 Vehicles" },

  // 🎬 Movies & TV Show
  { word: "Titanic", clue: "Iceberg", category: "🎬 Movies & TV Show" },
  { word: "Friends", clue: "Sofa", category: "🎬 Movies & TV Show" },
  { word: "Avatar", clue: "Blue", category: "🎬 Movies & TV Show" },
  { word: "Breaking Bad", clue: "Blue", category: "🎬 Movies & TV Show" },
  { word: "Harry Potter", clue: "Magic", category: "🎬 Movies & TV Show" },
  { word: "The Office", clue: "Paper", category: "🎬 Movies & TV Show" },
  { word: "Jaws", clue: "Teeth", category: "🎬 Movies & TV Show" },
  { word: "Stranger Things", clue: "Upside-down", category: "🎬 Movies & TV Show" },
  { word: "Frozen", clue: "Ice", category: "🎬 Movies & TV Show" },
  { word: "Game of Thrones", clue: "Iron", category: "🎬 Movies & TV Show" },
  { word: "The Matrix", clue: "Code", category: "🎬 Movies & TV Show" },
  { word: "Spongebob", clue: "Yellow", category: "🎬 Movies & TV Show" },
  { word: "Inception", clue: "Dream", category: "🎬 Movies & TV Show" },
  { word: "The Simpsons", clue: "Yellow", category: "🎬 Movies & TV Show" },
  { word: "Jurassic Park", clue: "Fossil", category: "🎬 Movies & TV Show" },

  // 🎨 Hobbies & Interests
  { word: "Reading", clue: "Story", category: "🎨 Hobbies & Interests" },
  { word: "Painting", clue: "Canvas", category: "🎨 Hobbies & Interests" },
  { word: "Gardening", clue: "Plant", category: "🎨 Hobbies & Interests" },
  { word: "Cooking", clue: "Recipe", category: "🎨 Hobbies & Interests" },
  { word: "Dancing", clue: "Music", category: "🎨 Hobbies & Interests" },
  { word: "Photography", clue: "Photo", category: "🎨 Hobbies & Interests" },
  { word: "Knitting", clue: "Yarn", category: "🎨 Hobbies & Interests" },
  { word: "Fishing", clue: "Lake", category: "🎨 Hobbies & Interests" },
  { word: "Hiking", clue: "Trail", category: "🎨 Hobbies & Interests" },
  { word: "Gaming", clue: "Play", category: "🎨 Hobbies & Interests" },
  { word: "Collecting", clue: "Hobby", category: "🎨 Hobbies & Interests" },
  { word: "Singing", clue: "Voice", category: "🎨 Hobbies & Interests" },
  { word: "Writing", clue: "Paper", category: "🎨 Hobbies & Interests" },
  { word: "Camping", clue: "Tent", category: "🎨 Hobbies & Interests" },
  { word: "Baking", clue: "Oven", category: "🎨 Hobbies & Interests" },

  // 🏠 Household Objects
  { word: "Refrigerator", clue: "Cold", category: "🏠 Household Objects" },
  { word: "Sofa", clue: "Sit", category: "🏠 Household Objects" },
  { word: "Lamp", clue: "Light", category: "🏠 Household Objects" },
  { word: "Microwave", clue: "Heat", category: "🏠 Household Objects" },
  { word: "Mirror", clue: "Reflect", category: "🏠 Household Objects" },
  { word: "Pillow", clue: "Soft", category: "🏠 Household Objects" },
  { word: "Vacuum", clue: "Clean", category: "🏠 Household Objects" },
  { word: "Clock", clue: "Time", category: "🏠 Household Objects" },
  { word: "Blender", clue: "Mix", category: "🏠 Household Objects" },
  { word: "Curtains", clue: "Window", category: "🏠 Household Objects" },
  { word: "Trash Can", clue: "Waste", category: "🏠 Household Objects" },
  { word: "Toaster", clue: "Bread", category: "🏠 Household Objects" },
  { word: "Fan", clue: "Air", category: "🏠 Household Objects" },
  { word: "Doormat", clue: "Welcome", category: "🏠 Household Objects" },
  { word: "Blanket", clue: "Warm", category: "🏠 Household Objects" }
];

export default gameWords;